---
apiVersion: v1
kind: Service
metadata:
  name: load-gen-service
  labels:
    app: load-gen
spec:
  type: LoadBalancer
  selector:
    app: load-gen
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000