---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: load-gen-webserver
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: load-gen-webserver-role
rules:
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["create"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: load-gen-webserver
subjects:
- kind: ServiceAccount
  name: load-gen-webserver
  namespace: default
roleRef:
  kind: ClusterRole
  name: load-gen-webserver-role
  apiGroup: rbac.authorization.k8s.io
